service: serverless-rekognition

plugins:
  - serverless-offline
  - serverless-plugin-custom-binary

custom:
  apigatewayBinary:
    types:
      - 'image/png'
      - 'image/jpeg'

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:*
      Resource: '*'

functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /
          method: GET
      - http: 
          path: /{proxy+}
          method: ANY
          contentHandling: CONVERT_TO_BINARY